spring:
  datasource:
    username: root
    password: lipanke
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.panke.entity